DELETE http://localhost:3000/api/books/547307

###
POST http://localhost:3000/api/books/
Content-Type: application/json

{
    "title": "My 6th Book",
    "author": "gourav punani",
    "year": "2007",
    "description": "this is my first book and it contains nothing"
}
###
PUT http://localhost:3000/api/books/
Content-Type: application/json

{
    "id": "5acc0789-f96e-4cca-b12d-8b9219913a2c",
    "title": "My 5th Book title changed",
    "author": "gourav punani",
    "year": "2007",
    "description": "5th book content updated"
}